version: '3.9'
services:
  fastapi:
    image: ${IMAGE_NAME}  # Specifies the name for the built image.
    build:
      context: .
      args:
        GIT_BRANCH_NAME: ${GIT_BRANCH_NAME}
        APP_DIR_NAME: ${APP_DIR_NAME}      
        GIT_URI: ${GIT_URI}      
      dockerfile: Dockerfile
    ports:
      - 8000:8000
   volumes:
      - ./cocolabhub.service:/etc/systemd/system/cocolabhub.service
    command: 
      - sleep infinity
      - sudo systemctl enable cocolabhub.service
    depends_on:
      - mongodb
  mongodb:
    container_name: ${CONTAINER_NAME_PREFIX}_mongodb
    image: mongo:7
    restart: always
    ports:
      - 27017:27017
